site_name: PHP Terminal
repo_url: https://github.com/alexandresalome/terminal/

docs_dir: docs
site_dir: build/doc

theme: readthedocs

nav:
  - Homepage: index.md
  - Installation: installation.md
  - Compatibility: compatibility.md
  - Usage:
    - Text manipulation: text.md
    - Color: color.md
    - Cursor: cursor.md
  - Going further:
    - How it works: how-it-works.md
    - References: references.md
    - Unhandled capabilities: unhandled-capabilities.md
    - Vocabulary: vocabulary.md

extra:
  version: 0.1

strict: true
